In [ ]:
from sklearn.svm import SVR
import numpy as np

In [ ]:
rango = np.arange(10,91,10)
rango

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
rango[0:3] # entrada 1

array([10, 20, 30])

In [ ]:
rango[3] #salida 1

40

In [ ]:
rango[1:4] # entrada 2

array([20, 30, 40])

In [ ]:
rango[4] # salida 2

50

In [ ]:
def crear_trenes(rango):
  n_pasos = 3
  x_train = []
  y_train = []

  for index_inicial in np.arange(0,len(rango)-3,1):
    index_final = index_inicial + n_pasos

    x_secuencia = rango[index_inicial:index_final]
    y_secuencia = rango[index_final]

    #print(x_secuencia, '    ', y_secuencia)

    x_train.append(x_secuencia)
    y_train.append(y_secuencia)

  x_train = np.array(x_train)
  y_train = np.array(y_train)

  return(x_train,y_train)

In [ ]:
np.shape(x_train) #numero muesras, numero de pasos

(6, 3)

### Lineal

In [ ]:
maquina_lineal = SVR(kernel='linear')
model_lineal = maquina_lineal.fit(x_train, y_train) # entrenamos

In [ ]:
x_pred = np.array([70,80,90])

In [ ]:
np.shape(x_pred)

(3,)

In [ ]:
x_pred = x_pred.reshape(1,3)

In [ ]:
np.shape(x_pred)

(1, 3)

In [ ]:
prediccion = model_lineal.predict(x_pred)

In [ ]:
prediccion

array([99.86])

### **Kernel Poly**

In [ ]:
maquia_poly =  SVR(kernel='poly')
model_poly = maquia_poly.fit(x_train, y_train) # entrenamos

In [ ]:
prediccion_poly = model_poly.predict(x_pred)
prediccion_poly

array([119.10353272])

### **Kernel RBF**

In [ ]:
maquia_rbf =  SVR(kernel='rbf', C = 10**10, gamma= 0.1)
model_rbf = maquia_rbf.fit(x_train, y_train) # entrenamos

In [ ]:
prediccion_rbf = model_rbf.predict(x_pred)
prediccion_rbf

array([65.])